### ISSUE TITLE
cv06 - modul search nevrací správné výsledky pro soubor cv06_test.txt

### ISSUE THREAD

**Issue by Noightmore** [Bahamut731lp/PJPA#1]
Při analýze testovacího souboru cv06_test.txt program vrací výsledky mimo maximální toleranci:

58
74
93
16

Správný výstup podle elearningu:

54
68
84
16

**Comment by Bahamut731lp** [comment]
Fixnuto - Regexy neměl jsem odfiltrované speciální znaky.
